# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vocab', '0003_relationship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.License'),
        ),
        migrations.AddField(
            model_name='term',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.License'),
        ),
    ]
